/* Write the SQL code to create the table structures for the entities shown in the figure below. The structures should contain the attributes specified in the ERD. Use data types that are appropriate for the data that will need to be stored in each attribute. Enforce primary key and foreign key constraints as indicated by the ERD. */


CREATE TABLE MEMBERSHIP(
	MEM_NUM INT not null auto_increment primary key,
	MEM_FNAME VARCHAR(255) CHARACTER SET utf8mb4,
	MEM_LNAME VARCHAR(255) CHARACTER SET utf8mb4,
	MEM_STREET VARCHAR(255) CHARACTER SET utf8mb4,
	MEM_CITY VARCHAR(255) CHARACTER SET utf8mb4,
	MEM_STATE VARCHAR(255) CHARACTER SET utf8mb4,
	MEM_ZIP CHAR(5),
	MEM_BALANCE DECIMAL(6,2)
);

CREATE TABLE PRICE(
	PRICE_CODE INT not null auto_increment primary key,
	PRICE_DESCRIPTION TEXT CHARACTER SET utf8mb4,
	PRICE_RENTFEE DECIMAL(5,2),
	PRICE_DAILYLATEFEE DECIMAL (5,2)
);

CREATE TABLE MOVIE(
	MOVIE_NUM INT not null auto_increment primary key,
	MOVIE_TITLE VARCHAR(255) CHARACTER SET utf8mb4,
	MOVIE_YEAR INT(4),
	MOVIE_COST DECIMAL(5,2),
	MOVIE_GENRE VARCHAR(255),
	PRICE_CODE INT,
	FOREIGN KEY(PRICE_CODE) REFERENCES PRICE(PRICE_CODE) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE RENTAL(
	RENT_NUM INT not null auto_increment primary key,
	RENT_DATE DATE,
	MEM_NUM INT,
	FOREIGN KEY(MEM_NUM) REFERENCES MEMBERSHIP(MEM_NUM) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE VIDEO(
	VID_NUM INT not null auto_increment primary key,
	VID_INDATE DATE,
	MOVIE_NUM INT,
	FOREIGN KEY (MOVIE_NUM) REFERENCES MOVIE(MOVIE_NUM) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE DETAILRENTAL(
	RENT_NUM INT,
	VID_NUM INT,
	DETAIL_FEE DECIMAL(5,2),
	DETAIL_DUEDATE DATE,
	DETAIL_RETURNDATE DATE,
	DETAIL_DAILYLATEFEE DECIMAL(5,2),
	PRIMARY KEY (RENT_NUM, VID_NUM),
	FOREIGN KEY (RENT_NUM) REFERENCES RENTAL(RENT_NUM) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (VID_NUM) REFERENCES VIDEO(VID_NUM) ON UPDATE CASCADE ON DELETE CASCADE
);