/* Write the query that will generate only the records that are unique to the CUSTOMER_2 table. */


SELECT DISTINCT CUST_LNAME, CUST_FNAME
FROM CUSTOMER_2
WHERE CUSTOMER_2.CUST_LNAME NOT IN(SELECT DISTINCT CUST_LNAME FROM CUSTOMER)
AND CUSTOMER_2.CUST_FNAME NOT IN(SELECT DISTINCT CUST_FNAME FROM CUSTOMER);