/* Write the queries to update the MOD_WAIT_CHG attribute values based on Problem 32. */


UPDATE MODEL SET MOD_WAIT_CHG = 100.00 WHERE MOD_CODE = "C-90A";
UPDATE MODEL SET MOD_WAIT_CHG = 50.00 WHERE MOD_CODE = "PA23-250";
UPDATE MODEL SET MOD_WAIT_CHG = 75.00 WHERE MOD_CODE = "PA23-350";